dist: trusty
language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn install --frozen-lockfile
  - yarn test
  - yarn build
deploy:
  provider: surge
  skip_cleanup: true
  domain: 1337.surge.sh
  project: ./build/
on:
  branch: master